import { SocketProvider } from "@/components/contexts/socket";
import { BreakProvider } from "@/components/contexts/break";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <SocketProvider>
          <BreakProvider>{children}</BreakProvider>
        </SocketProvider>
      </body>
    </html>
  );
}
