import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "@/styles/globals.css";
import SocketProvider from "@/components/contexts/socket";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <SocketProvider>{children}</SocketProvider>
      </body>
    </html>
  );
}
